export const ADD_DETAILS = "ADD_DETAILS";
export const SHOW_DETAILS = "SHOW_DETAILS";
export const DELETE_DETAILS = "DELETE_DETAILS";
export const UPDATE_DETAILS = "UPDATE_DETAILS";
export const ADD_COURSE_DETAILS = "ADD_COURSE_DETAILS";
export const SHOW_COURSE_DETAILS = "SHOW_COURSE_DETAILS";
export const DELETE_COURSE_DETAILS = "DELETE_COURSE_DETAILS";
export const UPDATE_COURSE_DETAILS = "UPDATE_COURSE_DETAILS";
